services:
  cockroachdb:
    image: cockroachdb/cockroach:v23.2.0
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data

  apply-migrations:
    build: ./backend
    command: >
      sh -c "while ! nc -z cockroachdb 26257; do sleep 1; done &&
      cd /app &&
      python -m alembic upgrade head &&
      tail -f /dev/null"
    depends_on:
      - cockroachdb
    volumes:
      - ./backend:/app

  fastapi:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - cockroachdb
      - apply-migrations
    volumes:
      - ./backend:/app

volumes:
  cockroach-data: