services:
  fastapi:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      cockroach:
        condition: service_healthy
    environment:
      - DATABASE_URL=cockroachdb+asyncpg://root@cockroach:26257/caulong_db
    volumes:
      - ./backend:/app
    restart: unless-stopped

  cockroach:
    image: cockroachdb/cockroach:v23.2.0
    container_name: cockroach
    ports:
      - "26257:26257"
      - "9080:9080"
    volumes:
      - cockroach_data:/var/lib/cockroach
    command: ["start-single-node", "--insecure"]
    healthcheck:
      test: ["CMD", "cockroach", "node", "status", "--insecure"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  cockroach_data: