services:
  cockroachdb:
    image: cockroachdb/cockroach:v23.2.0
    command: start-single-node --insecure --advertise-addr=0.0.0.0
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    healthcheck:
      test: ["CMD", "cockroach", "node", "status", "--insecure", "--host=localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  fastapi:
    build:
      context: ./backend  # <-- Изменили контекст на папку backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      cockroachdb:
        condition: service_healthy

volumes:
  cockroach-data: